baseURL = '/'
languageCode = 'en-us'
title = 'Pixelators'
enableRobotsTXT = true

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 2

[[menus.main]]
name = 'Seasons'
pageRef = '/seasons'
weight = 3

[[menus.main]]
name = 'Members'
pageRef = '/members'
weight = 4

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 5

[[menus.main]]
name = 'Sponsors'
pageRef = '/sponsors'
weight = 6

[[menus.main]]
name = 'Search'
pageRef = '/search'
weight = 99


[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
defaultTheme = "auto"
theme_color = "#e12f35"
#ShowBreadCrumbs = true

[params.assets]
theme_color = "#e12f35"
msapplication_TileColor = "#e12f35"

[params.label]
icon = "images/logo.avif"
alt = "Pixelators Logo"
iconHeight = 20

[[params.socialIcons]]
name = "github"
url = "https://github.com/Pixelators4014/"

[module]
[[module.imports]]
path = "hugo-notice"
